loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/a3e13a4a85ac4c2da17a6baab051ee1b.lua"))()
wait(0.1)
loadstring(game:HttpGet("https://raw.githubusercontent.com/tienkhanh1/spicy/main/Chilli.lua"))()
wait(0.5)
loadstring(game:HttpGet("https://pastebin.com/raw/5UxRfHDq"))()
